name: Build and Create Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**.gradle*', '**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: List all files for debugging
        run: ls -la # List all files to verify gradlew exists

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew
          ls -l ./gradlew  # Ensure the file is executable

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info -Dorg.gradle.jvmargs=-Xmx2048m


      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/libs/VillagerNoBreakingBlocks.jar
          body: |
            This is an automated release for version ${{ github.ref_name }}.
          token: ${{ secrets.GITHUB_TOKEN }}
