name: Build and Create Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure token has correct permissions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**.gradle*', '**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew
          ls -l ./gradlew  # Ensure the file is executable

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info -Dorg.gradle.jvmargs=-Xmx2048m

      - name: List build/libs directory
        run: ls -la build/libs  # Check the output directory for the JAR file

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0  # Ensure you are using a valid tag
          files: |
            build/libs/VillagerNoBreakingBlocks.jar  # Update this path based on the List step
          body: |
            This is an automated release for version v1.0.0.
          token: ${{ secrets.GITHUB_TOKEN }}
