name: Build and Create Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the distribution

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**.gradle*', '**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Build with Gradle
        run: gradle build

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/libs/VillagerNoBreakingBlocks.jar
          body: |
            This is an automated release for version ${{ github.ref_name }}.
          token: ${{ secrets.GITHUB_TOKEN }}